name: Build containers

on:
  push:
    branches: [ main ]
    paths:
      - 'docker/**'

jobs:
  prepare-matrix:
    runs-on: ubuntu-latest
    outputs:
      matrix: ${{ steps.set-matrix.outputs.matrix }}
    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 2

      - name: Prepare and Set Matrix
        id: set-matrix
        run: |
          matrix=""
          for dir in $(git diff --name-only ${{ github.event.before }} ${{ github.sha }} | grep 'docker/' | awk -F/ '{print $2}' | uniq); do
            image_name=$(grep 'FROM' ./docker/$dir/Dockerfile | awk '{print $2}' | head -n 1)
            manifest=$(docker manifest inspect $image_name || echo "{}")
            has_arm64=$(echo "$manifest" | jq -r '.manifests[]?.platform.architecture // empty' | grep -q 'arm64' && echo 'true' || echo 'false')
            archs='"amd64"'
            if [[ $has_arm64 == "true" ]]; then
              archs='"amd64", "arm64"'
            fi
            matrix_entry="{\"dir\": \"$dir\", \"arch\": [$archs]}"
            matrix="${matrix}${matrix:+,}${matrix_entry}"
          done
          matrix="{\"include\": [$matrix]}"
          echo "Matrix: $matrix"
          echo "::set-output name=matrix::$matrix"
        
  build:
    needs: prepare-matrix
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
      matrix: ${{fromJson(needs.prepare-matrix.outputs.matrix)}}
    permissions:
      contents: read
      packages: write
    steps:
      - uses: actions/checkout@v4

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Extract base image tag from Dockerfile
        run: echo "BASE_IMAGE_TAG=$(grep FROM docker/${{ matrix.dir }}/Dockerfile | awk -F':' '{print $2}' | awk -F' ' '{print $1}')" >> $GITHUB_ENV

      - name: Docker Login
        uses: docker/login-action@v3.0.0
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Build and push Docker image
        uses: docker/build-push-action@v6.5.0
        with:
            context: ./docker/${{ matrix.dir }}
            push: true
            tags: |
                ghcr.io/${{ github.repository }}/${{ matrix.dir }}:${{ github.sha }}
                ghcr.io/${{ github.repository }}/${{ matrix.dir }}:latest
                ghcr.io/${{ github.repository }}/${{ matrix.dir }}:${{ env.BASE_IMAGE_TAG }}
            platforms: ${{ join(matrix.arch, ',') }}